package v620.cc001.cloud01.app01.mservice.furtherstudy.impl;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.SQLException;
import java.sql.Timestamp;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;
import v620.cc001.base.common.dto.furtherstudy.PostgraduateMistakeBookEntryDto;
import v620.cc001.base.common.dto.furtherstudy.PostgraduateMistakeBookPageDto;
import v620.cc001.base.common.dto.furtherstudy.PostgraduateMistakeBookQueryRequest;
import v620.cc001.cloud01.app01.mservice.furtherstudy.PostgraduateMistakeBookStorage;
import v620.cc001.cloud01.app01.mservice.storage.PostgresqlStorageConfig;
import v620.cc001.cloud01.app01.mservice.storage.impl.PostgresqlStorageSupport;

public class PostgresqlPostgraduateMistakeBookStorage extends PostgresqlStorageSupport implements PostgraduateMistakeBookStorage {
    public PostgresqlPostgraduateMistakeBookStorage(PostgresqlStorageConfig config) { super(config, "postgraduate mistake book"); initialize(); }
    public PostgraduateMistakeBookEntryDto save(String userId, PostgraduateMistakeBookEntryDto value) { if (value == null) throw new IllegalArgumentException("错题记录不能为空。"); LocalDateTime now = LocalDateTime.now(); if (!text(value.getMistakeId())) value.setMistakeId("pmb-" + UUID.randomUUID().toString().replace("-", "")); value.setUserId(requireText(userId, "userId")); value.setCreatedAt(value.getCreatedAt() == null ? now : value.getCreatedAt()); value.setUpdatedAt(now); String sql = "INSERT INTO " + table("cc_postgraduate_mistake_book") + " (mistake_id,user_id,subject,question_text,wrong_answer,result_json,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?) ON CONFLICT (mistake_id) DO UPDATE SET subject=EXCLUDED.subject,question_text=EXCLUDED.question_text,wrong_answer=EXCLUDED.wrong_answer,result_json=EXCLUDED.result_json,updated_at=EXCLUDED.updated_at WHERE " + table("cc_postgraduate_mistake_book") + ".user_id=EXCLUDED.user_id"; Connection c=null; PreparedStatement s=null; try { c=connection(); s=c.prepareStatement(sql); int i=1; s.setString(i++, value.getMistakeId()); s.setString(i++, value.getUserId()); s.setString(i++, value.getSubject()); s.setString(i++, value.getQuestionText()); s.setString(i++, value.getWrongAnswer()); s.setString(i++, value.getResultJson()); s.setTimestamp(i++, timestamp(value.getCreatedAt())); s.setTimestamp(i, timestamp(value.getUpdatedAt())); s.executeUpdate(); return value; } catch(SQLException e) { throw storageException("save postgraduate mistake", e); } finally { close(s); close(c); } }
    public PostgraduateMistakeBookPageDto list(String userId, PostgraduateMistakeBookQueryRequest request) { int offset=request == null || request.getOffset()==null ? 0 : Math.max(0,request.getOffset().intValue()); int limit=request == null || request.getLimit()==null ? 20 : Math.min(100,Math.max(1,request.getLimit().intValue())); String sql="SELECT mistake_id,user_id,subject,question_text,created_at,updated_at FROM "+table("cc_postgraduate_mistake_book")+" WHERE user_id=? ORDER BY updated_at DESC LIMIT ? OFFSET ?"; List<PostgraduateMistakeBookEntryDto> items=new ArrayList<PostgraduateMistakeBookEntryDto>(); Connection c=null;PreparedStatement s=null;ResultSet r=null;try{c=connection();s=c.prepareStatement(sql);s.setString(1,requireText(userId,"userId"));s.setInt(2,limit+1);s.setInt(3,offset);r=s.executeQuery();while(r.next())items.add(entry(r,false));}catch(SQLException e){throw storageException("list postgraduate mistakes",e);}finally{close(r);close(s);close(c);} PostgraduateMistakeBookPageDto page=new PostgraduateMistakeBookPageDto(); boolean more=items.size()>limit;if(more)items.remove(items.size()-1);page.setItems(items);page.setHasMore(more);page.setNextOffset(offset+items.size());return page; }
    public PostgraduateMistakeBookEntryDto load(String userId, String mistakeId) { String sql="SELECT mistake_id,user_id,subject,question_text,wrong_answer,result_json,created_at,updated_at FROM "+table("cc_postgraduate_mistake_book")+" WHERE user_id=? AND mistake_id=?";Connection c=null;PreparedStatement s=null;ResultSet r=null;try{c=connection();s=c.prepareStatement(sql);s.setString(1,requireText(userId,"userId"));s.setString(2,requireText(mistakeId,"mistakeId"));r=s.executeQuery();return r.next()?entry(r,true):null;}catch(SQLException e){throw storageException("load postgraduate mistake",e);}finally{close(r);close(s);close(c);}}
    public boolean delete(String userId, String mistakeId) { String sql="DELETE FROM "+table("cc_postgraduate_mistake_book")+" WHERE user_id=? AND mistake_id=?"; Connection c=null; PreparedStatement s=null; try { c=connection(); s=c.prepareStatement(sql); s.setString(1, requireText(userId,"userId")); s.setString(2, requireText(mistakeId,"mistakeId")); return s.executeUpdate() > 0; } catch(SQLException e) { throw storageException("delete postgraduate mistake", e); } finally { close(s); close(c); } }
    private void initialize(){Connection c=null;Statement s=null;try{c=connection();s=c.createStatement();s.execute("CREATE TABLE IF NOT EXISTS "+table("cc_postgraduate_mistake_book")+" (mistake_id VARCHAR(128) PRIMARY KEY,user_id VARCHAR(128) NOT NULL,subject VARCHAR(255),question_text TEXT NOT NULL,wrong_answer TEXT,result_json TEXT NOT NULL,created_at TIMESTAMP NOT NULL,updated_at TIMESTAMP NOT NULL)");s.execute("CREATE INDEX IF NOT EXISTS cc_postgraduate_mistake_book_user_updated_idx ON "+table("cc_postgraduate_mistake_book")+" (user_id,updated_at DESC)");}catch(SQLException e){throw storageException("initialize postgraduate mistake book",e);}finally{close(s);close(c);}}
    private PostgraduateMistakeBookEntryDto entry(ResultSet r,boolean detail)throws SQLException{PostgraduateMistakeBookEntryDto v=new PostgraduateMistakeBookEntryDto();v.setMistakeId(r.getString(1));v.setUserId(r.getString(2));v.setSubject(r.getString(3));v.setQuestionText(r.getString(4));if(detail){v.setWrongAnswer(r.getString(5));v.setResultJson(r.getString(6));v.setCreatedAt(localDateTime(r.getTimestamp(7)));v.setUpdatedAt(localDateTime(r.getTimestamp(8)));}else{v.setCreatedAt(localDateTime(r.getTimestamp(5)));v.setUpdatedAt(localDateTime(r.getTimestamp(6)));}return v;} private boolean text(String v){return v!=null&&v.trim().length()>0;}
}
