package v620.cc001.cloud01.app01.mservice.furtherstudy.impl;

import java.sql.*;
import java.time.LocalDateTime;
import java.util.*;
import v620.cc001.base.common.dto.furtherstudy.*;
import v620.cc001.cloud01.app01.mservice.furtherstudy.FurtherStudyCompanionStorage;
import v620.cc001.cloud01.app01.mservice.storage.PostgresqlStorageConfig;
import v620.cc001.cloud01.app01.mservice.storage.impl.PostgresqlStorageSupport;

/** PostgreSQL storage for user-isolated further-study targets, records, materials and events. */
public class PostgresqlFurtherStudyCompanionStorage extends PostgresqlStorageSupport implements FurtherStudyCompanionStorage {
    public PostgresqlFurtherStudyCompanionStorage(PostgresqlStorageConfig config) { super(config, "further-study companion"); initialize(); }

    public FurtherStudyTargetDto saveTarget(String userId, FurtherStudyTargetDto value) {
        if (value == null) throw new IllegalArgumentException("Further-study target is required.");
        LocalDateTime now = LocalDateTime.now(); if (!text(value.getTargetId())) value.setTargetId(id("fst"));
        value.setUserId(requireText(userId, "userId")); value.setCreatedAt(value.getCreatedAt() == null ? now : value.getCreatedAt()); value.setUpdatedAt(now);
        if (!text(value.getStatus())) value.setStatus(FurtherStudyConstants.STATUS_IN_PROGRESS);
        String sql="INSERT INTO "+table("cc_further_study_target")+" (target_id,user_id,track,target_school,target_major,target_region,target_stage,status,target_json,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT (target_id) DO UPDATE SET track=EXCLUDED.track,target_school=EXCLUDED.target_school,target_major=EXCLUDED.target_major,target_region=EXCLUDED.target_region,target_stage=EXCLUDED.target_stage,status=EXCLUDED.status,target_json=EXCLUDED.target_json,updated_at=EXCLUDED.updated_at WHERE "+table("cc_further_study_target")+".user_id=EXCLUDED.user_id";
        Connection c=null; PreparedStatement s=null; try { c=connection(); s=c.prepareStatement(sql); int i=1; s.setString(i++,value.getTargetId());s.setString(i++,value.getUserId());s.setString(i++,value.getTrack());s.setString(i++,value.getTargetSchool());s.setString(i++,value.getTargetMajor());s.setString(i++,value.getTargetRegion());s.setString(i++,value.getTargetStage());s.setString(i++,value.getStatus());s.setString(i++,json(value.getTargetJson()));s.setTimestamp(i++,timestamp(value.getCreatedAt()));s.setTimestamp(i,timestamp(value.getUpdatedAt()));s.executeUpdate(); return value; } catch(SQLException e){throw storageException("save further-study target",e);} finally{close(s);close(c);} }

    public FurtherStudyRecordDetailDto saveRecord(String userId, FurtherStudyRecordDetailDto value) {
        if(value==null) throw new IllegalArgumentException("Further-study record is required."); LocalDateTime now=LocalDateTime.now(); boolean created=!text(value.getRecordId()); if(created)value.setRecordId(id("fsr")); value.setUserId(requireText(userId,"userId"));value.setCreatedAt(value.getCreatedAt()==null?now:value.getCreatedAt());value.setUpdatedAt(now);if(!text(value.getStatus()))value.setStatus(FurtherStudyConstants.STATUS_IN_PROGRESS);
        String sql="INSERT INTO "+table("cc_further_study_record")+" (record_id,user_id,track,record_type,target_id,title,status,target_school,target_major,target_region,exam_or_deadline_date,request_json,result_json,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT (record_id) DO UPDATE SET record_type=EXCLUDED.record_type,title=EXCLUDED.title,status=EXCLUDED.status,request_json=EXCLUDED.request_json,result_json=EXCLUDED.result_json,updated_at=EXCLUDED.updated_at WHERE "+table("cc_further_study_record")+".user_id=EXCLUDED.user_id";
        Connection c=null;PreparedStatement s=null;try{c=connection();s=c.prepareStatement(sql);int i=1;s.setString(i++,value.getRecordId());s.setString(i++,value.getUserId());s.setString(i++,value.getTrack());s.setString(i++,value.getRecordType());s.setString(i++,value.getTargetId());s.setString(i++,value.getTitle());s.setString(i++,value.getStatus());s.setString(i++,value.getTargetSchool());s.setString(i++,value.getTargetMajor());s.setString(i++,value.getTargetRegion());s.setObject(i++,value.getExamOrDeadlineDate());s.setString(i++,json(value.getRequestJson()));s.setString(i++,json(value.getResultJson()));s.setTimestamp(i++,timestamp(value.getCreatedAt()));s.setTimestamp(i,timestamp(value.getUpdatedAt()));s.executeUpdate();}catch(SQLException e){throw storageException("save further-study record",e);}finally{close(s);close(c);} appendEvent(value.getUserId(),event(value.getTrack(),value.getRecordId(),created?FurtherStudyConstants.EVENT_RECORD_CREATED:FurtherStudyConstants.EVENT_STATUS_UPDATED,created?"已保存升学分析结果":"已更新升学分析记录"));return value; }

    public List<FurtherStudyRecordSummaryDto> listRecords(String userId, FurtherStudyRecordQueryRequest q) { StringBuilder sql=new StringBuilder("SELECT record_id,user_id,track,record_type,target_id,title,status,target_school,target_major,target_region,exam_or_deadline_date,created_at,updated_at FROM ").append(table("cc_further_study_record")).append(" WHERE user_id=?"); List<Object> p=new ArrayList<Object>();p.add(requireText(userId,"userId")); if(q!=null&&text(q.getTrack())){sql.append(" AND track=?");p.add(q.getTrack().trim());}if(q!=null&&text(q.getRecordType())){sql.append(" AND record_type=?");p.add(q.getRecordType().trim());} sql.append(" ORDER BY updated_at DESC");if(q!=null&&q.getLimit()!=null)sql.append(" LIMIT ").append(Math.max(0,q.getLimit()));if(q!=null&&q.getOffset()!=null)sql.append(" OFFSET ").append(Math.max(0,q.getOffset())); List<FurtherStudyRecordSummaryDto> out=new ArrayList<FurtherStudyRecordSummaryDto>();Connection c=null;PreparedStatement s=null;ResultSet r=null;try{c=connection();s=c.prepareStatement(sql.toString());for(int i=0;i<p.size();i++)s.setObject(i+1,p.get(i));r=s.executeQuery();while(r.next())out.add(record(r,false));return out;}catch(SQLException e){throw storageException("list further-study records",e);}finally{close(r);close(s);close(c);} }
    public FurtherStudyRecordDetailDto loadRecord(String userId,String recordId){String sql="SELECT record_id,user_id,track,record_type,target_id,title,status,target_school,target_major,target_region,exam_or_deadline_date,created_at,updated_at,request_json::text,result_json::text FROM "+table("cc_further_study_record")+" WHERE user_id=? AND record_id=?";Connection c=null;PreparedStatement s=null;ResultSet r=null;try{c=connection();s=c.prepareStatement(sql);s.setString(1,requireText(userId,"userId"));s.setString(2,requireText(recordId,"recordId"));r=s.executeQuery();return r.next()?record(r,true):null;}catch(SQLException e){throw storageException("load further-study record",e);}finally{close(r);close(s);close(c);} }
    public FurtherStudyRecordDetailDto updateRecordStatus(String userId,FurtherStudyRecordStatusUpdateRequest request){FurtherStudyRecordDetailDto r=loadRecord(userId,request.getRecordId());if(r==null)throw new IllegalArgumentException("Further-study record was not found.");r.setStatus(request.getStatus());return saveRecord(userId,r);}
    public FurtherStudyMaterialDto saveMaterial(String userId,FurtherStudyMaterialDto m){if(m==null)throw new IllegalArgumentException("Further-study material is required.");LocalDateTime now=LocalDateTime.now();if(!text(m.getMaterialId()))m.setMaterialId(id("fsm"));m.setUserId(requireText(userId,"userId"));m.setCreatedAt(m.getCreatedAt()==null?now:m.getCreatedAt());m.setUpdatedAt(now);if(!text(m.getStatus()))m.setStatus(FurtherStudyConstants.STATUS_IN_PROGRESS);String sql="INSERT INTO "+table("cc_further_study_material")+" (material_id,user_id,track,record_id,material_type,title,status,file_key,content_json,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT (material_id) DO UPDATE SET title=EXCLUDED.title,status=EXCLUDED.status,content_json=EXCLUDED.content_json,updated_at=EXCLUDED.updated_at WHERE "+table("cc_further_study_material")+".user_id=EXCLUDED.user_id";Connection c=null;PreparedStatement s=null;try{c=connection();s=c.prepareStatement(sql);int i=1;s.setString(i++,m.getMaterialId());s.setString(i++,m.getUserId());s.setString(i++,m.getTrack());s.setString(i++,m.getRecordId());s.setString(i++,m.getMaterialType());s.setString(i++,m.getTitle());s.setString(i++,m.getStatus());s.setString(i++,m.getFileKey());s.setString(i++,json(m.getContentJson()));s.setTimestamp(i++,timestamp(m.getCreatedAt()));s.setTimestamp(i,timestamp(m.getUpdatedAt()));s.executeUpdate();return m;}catch(SQLException e){throw storageException("save further-study material",e);}finally{close(s);close(c);}}
    public List<FurtherStudyMaterialDto> listMaterials(String userId,String track,String recordId){String sql="SELECT material_id,user_id,track,record_id,material_type,title,status,file_key,content_json::text,created_at,updated_at FROM "+table("cc_further_study_material")+" WHERE user_id=? AND (? IS NULL OR track=?) AND (? IS NULL OR record_id=?) ORDER BY updated_at DESC";List<FurtherStudyMaterialDto> out=new ArrayList<FurtherStudyMaterialDto>();Connection c=null;PreparedStatement s=null;ResultSet r=null;try{c=connection();s=c.prepareStatement(sql);s.setString(1,requireText(userId,"userId"));s.setString(2,blank(track));s.setString(3,blank(track));s.setString(4,blank(recordId));s.setString(5,blank(recordId));r=s.executeQuery();while(r.next())out.add(material(r));return out;}catch(SQLException e){throw storageException("list further-study materials",e);}finally{close(r);close(s);close(c);}}
    public FurtherStudyEventDto appendEvent(String userId,FurtherStudyEventDto e){if(e==null)throw new IllegalArgumentException("Further-study event is required.");if(!text(e.getEventId()))e.setEventId(id("fse"));e.setUserId(requireText(userId,"userId"));if(e.getCreatedAt()==null)e.setCreatedAt(LocalDateTime.now());String sql="INSERT INTO "+table("cc_further_study_event")+" (event_id,user_id,track,record_id,event_type,summary,event_json,created_at) VALUES (?,?,?,?,?,?,?,?)";Connection c=null;PreparedStatement s=null;try{c=connection();s=c.prepareStatement(sql);s.setString(1,e.getEventId());s.setString(2,e.getUserId());s.setString(3,e.getTrack());s.setString(4,e.getRecordId());s.setString(5,e.getEventType());s.setString(6,e.getSummary());s.setString(7,json(e.getEventJson()));s.setTimestamp(8,timestamp(e.getCreatedAt()));s.executeUpdate();return e;}catch(SQLException x){throw storageException("save further-study event",x);}finally{close(s);close(c);}}
    public List<FurtherStudyEventDto> listEvents(String userId,String recordId){String sql="SELECT event_id,user_id,track,record_id,event_type,summary,event_json::text,created_at FROM "+table("cc_further_study_event")+" WHERE user_id=? AND record_id=? ORDER BY created_at";List<FurtherStudyEventDto>out=new ArrayList<FurtherStudyEventDto>();Connection c=null;PreparedStatement s=null;ResultSet r=null;try{c=connection();s=c.prepareStatement(sql);s.setString(1,requireText(userId,"userId"));s.setString(2,requireText(recordId,"recordId"));r=s.executeQuery();while(r.next()){FurtherStudyEventDto e=new FurtherStudyEventDto();e.setEventId(r.getString(1));e.setUserId(r.getString(2));e.setTrack(r.getString(3));e.setRecordId(r.getString(4));e.setEventType(r.getString(5));e.setSummary(r.getString(6));e.setEventJson(r.getString(7));e.setCreatedAt(localDateTime(r.getTimestamp(8)));out.add(e);}return out;}catch(SQLException e){throw storageException("list further-study events",e);}finally{close(r);close(s);close(c);}}
    private void initialize(){Connection c=null;Statement s=null;try{c=connection();s=c.createStatement();s.execute("CREATE TABLE IF NOT EXISTS "+table("cc_further_study_target")+" (target_id VARCHAR(128) PRIMARY KEY,user_id VARCHAR(128) NOT NULL,track VARCHAR(64) NOT NULL,target_school VARCHAR(255),target_major VARCHAR(255),target_region VARCHAR(255),target_stage VARCHAR(128),status VARCHAR(64),target_json TEXT NOT NULL,created_at TIMESTAMP NOT NULL,updated_at TIMESTAMP NOT NULL)");s.execute("CREATE TABLE IF NOT EXISTS "+table("cc_further_study_record")+" (record_id VARCHAR(128) PRIMARY KEY,user_id VARCHAR(128) NOT NULL,track VARCHAR(64) NOT NULL,record_type VARCHAR(128) NOT NULL,target_id VARCHAR(128),title VARCHAR(512),status VARCHAR(64),target_school VARCHAR(255),target_major VARCHAR(255),target_region VARCHAR(255),exam_or_deadline_date DATE,request_json TEXT NOT NULL,result_json TEXT NOT NULL,created_at TIMESTAMP NOT NULL,updated_at TIMESTAMP NOT NULL)");s.execute("CREATE TABLE IF NOT EXISTS "+table("cc_further_study_material")+" (material_id VARCHAR(128) PRIMARY KEY,user_id VARCHAR(128) NOT NULL,track VARCHAR(64) NOT NULL,record_id VARCHAR(128),material_type VARCHAR(128),title VARCHAR(512),status VARCHAR(64),file_key VARCHAR(1024),content_json TEXT NOT NULL,created_at TIMESTAMP NOT NULL,updated_at TIMESTAMP NOT NULL)");s.execute("CREATE TABLE IF NOT EXISTS "+table("cc_further_study_event")+" (event_id VARCHAR(128) PRIMARY KEY,user_id VARCHAR(128) NOT NULL,track VARCHAR(64),record_id VARCHAR(128),event_type VARCHAR(128),summary VARCHAR(1024),event_json TEXT NOT NULL,created_at TIMESTAMP NOT NULL)");}catch(SQLException e){throw storageException("initialize further-study tables",e);}finally{close(s);close(c);}}
    private FurtherStudyRecordDetailDto record(ResultSet r,boolean detail)throws SQLException{FurtherStudyRecordDetailDto v=new FurtherStudyRecordDetailDto();v.setRecordId(r.getString(1));v.setUserId(r.getString(2));v.setTrack(r.getString(3));v.setRecordType(r.getString(4));v.setTargetId(r.getString(5));v.setTitle(r.getString(6));v.setStatus(r.getString(7));v.setTargetSchool(r.getString(8));v.setTargetMajor(r.getString(9));v.setTargetRegion(r.getString(10));java.sql.Date d=r.getDate(11);v.setExamOrDeadlineDate(d==null?null:d.toLocalDate());v.setCreatedAt(localDateTime(r.getTimestamp(12)));v.setUpdatedAt(localDateTime(r.getTimestamp(13)));if(detail){v.setRequestJson(r.getString(14));v.setResultJson(r.getString(15));}return v;} private FurtherStudyMaterialDto material(ResultSet r)throws SQLException{FurtherStudyMaterialDto m=new FurtherStudyMaterialDto();m.setMaterialId(r.getString(1));m.setUserId(r.getString(2));m.setTrack(r.getString(3));m.setRecordId(r.getString(4));m.setMaterialType(r.getString(5));m.setTitle(r.getString(6));m.setStatus(r.getString(7));m.setFileKey(r.getString(8));m.setContentJson(r.getString(9));m.setCreatedAt(localDateTime(r.getTimestamp(10)));m.setUpdatedAt(localDateTime(r.getTimestamp(11)));return m;} private FurtherStudyEventDto event(String t,String r,String type,String summary){FurtherStudyEventDto e=new FurtherStudyEventDto();e.setTrack(t);e.setRecordId(r);e.setEventType(type);e.setSummary(summary);e.setEventJson("{}");return e;}private String id(String p){return p+"-"+UUID.randomUUID().toString().replace("-","");}private boolean text(String v){return v!=null&&v.trim().length()>0;}private String blank(String v){return text(v)?v.trim():null;}private String json(String v){return text(v)?v:"{}";}
}
