/**
 * This is a kingdee cosmic template project that is automatically generated by the Kingdee cosmic development assistant plugin. 
 * If there are any issues during the use process, you can provide feedback to the kingdee developer community website.
 * Website: https://developer.kingdee.com/developer?productLineId=29
 * Author: liebin.zheng
 * Generate Date: 2026-05-12 17:21:40
 */
package v620.cosmic.debug;

import kd.cosmic.debug.tools.CosmicLauncher;

import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.Properties;

/**
 * 启动本地应用程序(微服务节点)
 */
public class DebugApplication {

    private static final String LOCAL_CONFIG_FILE = "debug-local.properties";
    private static final String SHARED_RUNTIME_PROPERTY = "cc001.shared.runtime.enabled";
    private static final Properties LOCAL_CONFIG = loadLocalConfig();

    public static void main(String[] args) {
    	
//    	Thread.currentThread().setContextClassLoader(new KDSecurityClassLoader(Thread.currentThread().getContextClassLoader()));
    	
        CosmicLauncher cosmic = new CosmicLauncher(false);

        String serverHost = config("cosmic.server.host", "COSMIC_SERVER_HOST", "127.0.0.1");
        String zkUser = config("cosmic.zk.user", "COSMIC_ZK_USER", "zookeeper");
        String zkPassword = config("cosmic.zk.password", "COSMIC_ZK_PASSWORD", "");
        String configUrl = config("cosmic.config.url", "COSMIC_CONFIG_URL",
                buildConfigUrl(serverHost, intConfig("cosmic.zk.port", "COSMIC_ZK_PORT", 2181), zkUser, zkPassword));
        String mcUrl = config("cosmic.mc.url", "COSMIC_MC_URL",
                "http://" + serverHost + ":" + intConfig("cosmic.mc.port", "COSMIC_MC_PORT", 8090) + "/");
        String monitorEsUrl = config("cosmic.monitor.es.url", "COSMIC_MONITOR_ES_URL",
                config("vector.es.url", "VECTOR_ES_URL", "http://" + serverHost + ":9200/"));

        cosmic.setClusterNumber(config("cosmic.cluster.number", "COSMIC_CLUSTER_NUMBER", "cosmic"));
        cosmic.setTenantNumber(config("cosmic.tenant.number", "COSMIC_TENANT_NUMBER", "ierp"));
        cosmic.setConfigUrl(configUrl);
        cosmic.setMcServerUrl(mcUrl);
        cosmic.set("monitor.es.url", monitorEsUrl);
        cosmic.set("gov.reporter.es.url", monitorEsUrl);
        setDefault("cc001.identity.adapter.enabled", "true");
        setDefault("cc001.identity.login.provider.enabled", "true");
        setDefault("cc001.identity.login.provider.name", "RequestContext");
        setDefault("cc001.file.adapter.enabled", "true");
        configureStorage();
        configureAgentPlatform();
        configureSharedRuntime();
        cosmic.set("server.bind.ip", config("cosmic.web.bind.ip", "COSMIC_WEB_BIND_IP", "0.0.0.0"));
        
        // 自定义本地苍穹调试服务的端口
        int webPort = intConfig("cosmic.web.port", "COSMIC_WEB_PORT", 8881);
        cosmic.setCosmicWebPort(webPort);
        cosmic.set("domain.contextUrl", config("cosmic.web.public.url", "COSMIC_WEB_PUBLIC_URL",
                "http://" + serverHost + ":" + webPort + "/ierp"));

        cosmic.start();
    }

    private static void configureStorage() {
        setConfiguredProperty("cc001.profile.storage.adapter", "CC001_PROFILE_STORAGE_ADAPTER");
        setConfiguredProperty("cc001.profile.postgresql.url", "CC001_PROFILE_POSTGRESQL_URL");
        setConfiguredProperty("cc001.profile.postgresql.username", "CC001_PROFILE_POSTGRESQL_USERNAME");
        setConfiguredProperty("cc001.profile.postgresql.password", "CC001_PROFILE_POSTGRESQL_PASSWORD");
        setConfiguredProperty("cc001.profile.postgresql.schema", "CC001_PROFILE_POSTGRESQL_SCHEMA");
        setConfiguredProperty("cc001.profile.postgresql.initialize", "CC001_PROFILE_POSTGRESQL_INITIALIZE");
        setConfiguredProperty("cc001.storage.backend", "CC001_STORAGE_BACKEND");
        setConfiguredProperty("cc001.storage.postgresql.url", "CC001_STORAGE_POSTGRESQL_URL");
        setConfiguredProperty("cc001.storage.postgresql.username", "CC001_STORAGE_POSTGRESQL_USERNAME");
        setConfiguredProperty("cc001.storage.postgresql.password", "CC001_STORAGE_POSTGRESQL_PASSWORD");
        setConfiguredProperty("cc001.storage.postgresql.schema", "CC001_STORAGE_POSTGRESQL_SCHEMA");
        setConfiguredProperty("cc001.storage.postgresql.initialize", "CC001_STORAGE_POSTGRESQL_INITIALIZE");
        copyIfMissing("cc001.storage.backend", "cc001.profile.storage.adapter");
        copyIfMissing("cc001.storage.postgresql.url", "cc001.profile.postgresql.url");
        copyIfMissing("cc001.storage.postgresql.username", "cc001.profile.postgresql.username");
        copyIfMissing("cc001.storage.postgresql.password", "cc001.profile.postgresql.password");
        copyIfMissing("cc001.storage.postgresql.schema", "cc001.profile.postgresql.schema");
        copyIfMissing("cc001.storage.postgresql.initialize", "cc001.profile.postgresql.initialize");
    }

    static void configureAgentPlatform() {
        setConfiguredProperty("cc001.agent.platform.profile.enabled",
                "CC001_AGENT_PLATFORM_PROFILE_ENABLED");
        setConfiguredProperty("cc001.agent.platform.profile.agentNumber",
                "CC001_AGENT_PLATFORM_PROFILE_AGENTNUMBER");
        setConfiguredProperty("cc001.agent.platform.profile.taskFlowCode",
                "CC001_AGENT_PLATFORM_PROFILE_TASKFLOWCODE");
        setConfiguredProperty("cc001.agent.platform.resume.enabled",
                "CC001_AGENT_PLATFORM_RESUME_ENABLED");
        setConfiguredProperty("cc001.agent.platform.resume.agentNumber",
                "CC001_AGENT_PLATFORM_RESUME_AGENTNUMBER");
        setConfiguredProperty("cc001.agent.platform.resume.taskFlowCode",
                "CC001_AGENT_PLATFORM_RESUME_TASKFLOWCODE");
        setConfiguredProperty("cc001.agent.platform.employment.enabled",
                "CC001_AGENT_PLATFORM_EMPLOYMENT_ENABLED");
        setConfiguredProperty("cc001.agent.platform.employment.agentNumber",
                "CC001_AGENT_PLATFORM_EMPLOYMENT_AGENTNUMBER");
        setConfiguredProperty("cc001.agent.platform.employment.taskFlowCode",
                "CC001_AGENT_PLATFORM_EMPLOYMENT_TASKFLOWCODE");
        setConfiguredProperty("cc001.agent.platform.study.postgraduate.enabled",
                "CC001_AGENT_PLATFORM_STUDY_POSTGRADUATE_ENABLED");
        setConfiguredProperty("cc001.agent.platform.study.postgraduate.agentNumber",
                "CC001_AGENT_PLATFORM_STUDY_POSTGRADUATE_AGENTNUMBER");
        setConfiguredProperty("cc001.agent.platform.study.postgraduate.taskFlowCode",
                "CC001_AGENT_PLATFORM_STUDY_POSTGRADUATE_TASKFLOWCODE");
        setConfiguredProperty("cc001.agent.platform.study.recommendation.enabled",
                "CC001_AGENT_PLATFORM_STUDY_RECOMMENDATION_ENABLED");
        setConfiguredProperty("cc001.agent.platform.study.recommendation.agentNumber",
                "CC001_AGENT_PLATFORM_STUDY_RECOMMENDATION_AGENTNUMBER");
        setConfiguredProperty("cc001.agent.platform.study.abroad.enabled",
                "CC001_AGENT_PLATFORM_STUDY_ABROAD_ENABLED");
        setConfiguredProperty("cc001.agent.platform.study.abroad.agentNumber",
                "CC001_AGENT_PLATFORM_STUDY_ABROAD_AGENTNUMBER");
        setConfiguredProperty("cc001.agent.platform.study.abroad.taskFlowCode",
                "CC001_AGENT_PLATFORM_STUDY_ABROAD_TASKFLOWCODE");
    }

    private static void configureSharedRuntime() {
        boolean sharedRuntime = Boolean.parseBoolean(config("cosmic.shared.runtime.enabled",
                "COSMIC_SHARED_RUNTIME_ENABLED", "true"));
        System.setProperty(SHARED_RUNTIME_PROPERTY, String.valueOf(sharedRuntime));
        if (sharedRuntime) {
            validateSharedPostgresql();
        }
    }

    private static void validateSharedPostgresql() {
        validateSharedStorageConfiguration();
        String url = System.getProperty("cc001.storage.postgresql.url");
        String username = System.getProperty("cc001.storage.postgresql.username");
        String password = System.getProperty("cc001.storage.postgresql.password");
        try {
            Class.forName("org.postgresql.Driver");
            Connection connection = DriverManager.getConnection(url, username, password);
            try {
                connection.close();
            } catch (SQLException ignored) {
                // The successful connection already proves the configured endpoint is reachable.
            }
        } catch (ClassNotFoundException e) {
            throw new IllegalStateException("Shared runtime requires the PostgreSQL JDBC driver.", e);
        } catch (SQLException e) {
            throw new IllegalStateException("Shared runtime cannot connect to the configured PostgreSQL storage.", e);
        }
    }

    static void validateSharedStorageConfiguration() {
        String backend = System.getProperty("cc001.storage.backend");
        String url = System.getProperty("cc001.storage.postgresql.url");
        String username = System.getProperty("cc001.storage.postgresql.username");
        String password = System.getProperty("cc001.storage.postgresql.password");
        String schema = System.getProperty("cc001.storage.postgresql.schema");
        if (!"postgresql".equalsIgnoreCase(trim(backend)) || isBlank(url) || isBlank(username)
                || isBlank(password) || isBlank(schema)) {
            throw new IllegalStateException("Shared runtime requires complete PostgreSQL storage configuration.");
        }
    }

    private static String buildConfigUrl(String host, int port, String user, String password) {
        String connectString = host + ":" + port;
        if (isBlank(user) || isBlank(password)) {
            return connectString;
        }
        return connectString + "?user=" + user + "&password=" + password;
    }

    private static int intConfig(String propertyKey, String envKey, int defaultValue) {
        String value = config(propertyKey, envKey, String.valueOf(defaultValue));
        try {
            return Integer.parseInt(value);
        } catch (NumberFormatException e) {
            return defaultValue;
        }
    }

    private static String config(String propertyKey, String envKey, String defaultValue) {
        String value = System.getProperty(propertyKey);
        if (!isBlank(value)) {
            return value.trim();
        }
        value = System.getenv(envKey);
        if (!isBlank(value)) {
            return value.trim();
        }
        value = LOCAL_CONFIG.getProperty(propertyKey);
        if (!isBlank(value)) {
            return value.trim();
        }
        return defaultValue;
    }

    private static void setDefault(String key, String value) {
        if (isBlank(System.getProperty(key))) {
            System.setProperty(key, value);
        }
    }

    private static void setConfiguredProperty(String propertyKey, String envKey) {
        String value = config(propertyKey, envKey, "");
        if (!isBlank(value)) {
            System.setProperty(propertyKey, value);
        }
    }

    private static void copyIfMissing(String targetKey, String sourceKey) {
        if (isBlank(System.getProperty(targetKey)) && !isBlank(System.getProperty(sourceKey))) {
            System.setProperty(targetKey, System.getProperty(sourceKey));
        }
    }

    private static String trim(String value) {
        return value == null ? "" : value.trim();
    }

    private static Properties loadLocalConfig() {
        Properties properties = new Properties();
        File file = findLocalConfig();
        if (file == null || !file.isFile()) {
            return properties;
        }

        FileInputStream input = null;
        try {
            input = new FileInputStream(file);
            properties.load(input);
        } catch (IOException e) {
            throw new IllegalStateException("Unable to load " + file.getAbsolutePath(), e);
        } finally {
            if (input != null) {
                try {
                    input.close();
                } catch (IOException ignored) {
                    // Ignore close failure for local debug configuration.
                }
            }
        }
        return properties;
    }

    private static File findLocalConfig() {
        File dir = new File(System.getProperty("user.dir"));
        while (dir != null) {
            File file = new File(dir, LOCAL_CONFIG_FILE);
            if (file.isFile()) {
                return file;
            }
            dir = dir.getParentFile();
        }
        return null;
    }

    private static boolean isBlank(String value) {
        return value == null || value.trim().length() == 0;
    }
}
