package v620.cc001.cloud01.app01.mservice.ai;

/** Server-side boundary for the thirteen further-study companion analysis tasks. */
public interface FurtherStudyCompanionAnalyzer {

    String POSTGRADUATE_SCHOOL_RECOMMEND = "POSTGRADUATE_SCHOOL_RECOMMEND";
    String POSTGRADUATE_PLAN_GENERATE = "POSTGRADUATE_PLAN_GENERATE";
    String POSTGRADUATE_MISTAKE_ANALYZE = "POSTGRADUATE_MISTAKE_ANALYZE";
    String POSTGRADUATE_REEXAM_PREPARE = "POSTGRADUATE_REEXAM_PREPARE";

    String RECOMMENDATION_DIAGNOSE = "RECOMMENDATION_DIAGNOSE";
    String RECOMMENDATION_PLAN_GENERATE = "RECOMMENDATION_PLAN_GENERATE";
    String RECOMMENDATION_DOCUMENT_POLISH = "RECOMMENDATION_DOCUMENT_POLISH";
    String RECOMMENDATION_TUTOR_LETTER = "RECOMMENDATION_TUTOR_LETTER";

    String STUDY_ABROAD_PROFILE_DIAGNOSE = "STUDY_ABROAD_PROFILE_DIAGNOSE";
    String STUDY_ABROAD_LANGUAGE_PLAN = "STUDY_ABROAD_LANGUAGE_PLAN";
    String STUDY_ABROAD_SCHOOL_POSITION = "STUDY_ABROAD_SCHOOL_POSITION";
    String STUDY_ABROAD_STATEMENT_OUTLINE = "STUDY_ABROAD_STATEMENT_OUTLINE";
    String STUDY_ABROAD_VISA_CHECKLIST = "STUDY_ABROAD_VISA_CHECKLIST";

    <T> T analyze(String userId, String taskType, Object payload, Class<T> resultType);
}
